#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "emby-server"
name = "Emby"
description.en = "Personal media server"
description.fr = "Serveur multimédia personnel"

version = "4.9.3.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0"
website = "https://emby.media/"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/MediaBrowser/Emby.Releases"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/emby"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/MediaBrowser/Emby.Releases/releases/download/4.9.3.0/emby-server-deb_4.9.3.0_amd64.deb"
    sha256 = "4edf8fe819d89b979f4aebbab05f598bbabf44b87f460fb3222e6912a8b0a733"
    format = "whatever"
    extract = false
    rename = "emby-server.deb"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8096
