#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass http://127.0.0.1:__PORT__/;  ## Enter the IP and port of the backend emby server here.

  proxy_hide_header X-Powered-By;  ## Hides nginx server version from bad guys.
  proxy_set_header Range $http_range;  ## Allows specific chunks of a file to be requested.
  proxy_set_header If-Range $http_if_range;  ## Allows specific chunks of a file to be requested.
  proxy_set_header X-Real-IP $remote_addr;  ## Passes the real client IP to the backend server.
  #proxy_set_header X-Real-IP $http_CF_Connecting_IP;  ## if you use cloudflare un-comment this line and comment out above line.
  proxy_set_header Host $host;  ## Passes the requested domain name to the backend server.
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  ## Adds forwarded IP to the list of IPs that were forwarded to the backend server.

  ## ADDITIONAL SECURITY SETTINGS ##
  ## Optional settings to improve security ##
  ## add these after you have completed your testing and ssl setup ##
  ## NOTICE: For the Strict-Transport-Security setting below, I would recommend ramping up to this value ##
  ##         See https://hstspreload.org/ read through the "Deployment Recommendations" section first!   ##
  #add_header 'Referrer-Policy' 'origin-when-cross-origin';
  #add_header Strict-Transport-Security "max-age=15552000; preload" always;
  #add_header X-Frame-Options "SAMEORIGIN" always;
  #add_header X-Content-Type-Options "nosniff" always;
  #add_header X-XSS-Protection "1; mode=block" always;

  ## WEBSOCKET SETTINGS ## Used to pass two way real time info to and from emby and the client.
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
}
