#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Create the temporary directory
tempdir="$(mktemp -d)"

ynh_setup_source --dest_dir="$tempdir"

_ynh_apt_install --allow-downgrades "$tempdir/emby-server-deb_4.8.11.0_amd64.deb"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
#ynh_config_add_systemd

#yunohost service add "$app-serveur" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-serveur" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
