#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Stop and disable the systemd service
ynh_systemctl --service="$app" --action="stop"
systemctl disable emby-server.service --quiet

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the nginx configuration
ynh_config_remove_nginx

# Remove the .deb package
_ynh_apt_remove "emby-server"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
