#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Create the temporary directory
tempdir="$(mktemp -d)"

ynh_setup_source --dest_dir="$tempdir"

_ynh_apt_install --allow-downgrades "$tempdir/emby-server.deb"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Reload systemd to pick up any changes from the new .deb package
systemctl daemon-reload

# Enable the service (in case it was disabled)
systemctl enable emby-server.service --quiet

# Update the nginx configuration
ynh_config_add_nginx

# Update the service registration with Yunohost
yunohost service update "$app" --description="Emby Server - Personal media server" --log="/var/log/$app/$app.log" --test_status="systemctl is-active emby-server"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
